### ISSUE TITLE
requesting google font via http - should be https

### ISSUE THREAD

**Issue by jhnpldng** [b2evolution/flat_skin#1]
This theme is requesting http://fonts.googleapi instead of https://

**Comment by yurabakhtin** [comment]
Fixed in commits https://github.com/b2evolution/flat_skin/commit/dba1f6ef7a6bc78c815731740b4f62d379631855, https://github.com/b2evolution/flat_skin/commit/96b57c4f9a9ff4b0f62e28c9be9424c302ada0a4.
