### ISSUE TITLE
Also 404 for jquery.nicescroll

### ISSUE THREAD

**Issue by jhnpldng** [b2evolution/flat_skin#2]
Also 404 for jquery.nicescroll
![http](https://user-images.githubusercontent.com/8770215/53053208-62c69200-3466-11e9-85f1-a9e104cb572d.png)
-----------------------------
scratch that - not coming from b2evo

**Comment by yurabakhtin** [comment]
Fixed in commit https://github.com/b2evolution/flat_skin/commit/dba1f6ef7a6bc78c815731740b4f62d379631855.
