### ISSUE TITLE
Can't tweak navbar css

### ISSUE THREAD

**Issue by jhnpldng** [b2evolution/flat_skin#3]
I've tried overriding navbar styles in style.css and in evo back office with no luck. Could we move styles out of various css files in rsc directory and into style.css?
Again, this is a main menu and the site owner should have full control over styling it. I'm able to override colors and fonts but not padding. I'm making copies of the bootstrap skins as well as flat_skin.

vendor-prefixes.less
`@media (min-width: 768px)
.navbar-nav>li>a {
    padding-top: 15px;
    padding-bottom: 15px;
}`

also navbar.less which is in rsc folder as above vendor-prefixes.css is
`.navbar-nav>li>a {
    padding-top: 10px;
    padding-bottom: 10px;
    line-height: 20px;
}`

but wait, there's more
rsc/css/bootstrap/bootstrap.css
`.nav>li>a {
    position: relative;
    display: block;
    padding: 10px 15px;
}`

1 navbar styled from 3 css/less files makes my head hurt

Had the same situation with sitewide_header but you took care of that, Thank You, Thank You, Thank You
imho every style/element that makes up the front office should be in a skin folder. Even stuff like table, input etc so we can style 100% of our site.

no rush, maybe v7? (I know, things will work different with v7 - hopefully flat_skin will still work - if not, I won't be upgrading as I don't care for the tabs menu)

thanks, poorboy | poorboy2 | jhnpldng aka John

**Comment by fplanque** [comment]
It is common practice to have multiple CSS files override each other. That's what the C in CSS stands for (Cascadinfg Style Sheets).
Any style can ALWAYS be overriden to make it match what you want. You just need to make a selector that is more specific than others. For example `div.nav>li>a` is more specific than `.nav>li>a` and will override anything defined for `.nav>li>a`.

**Comment by jhnpldng** [comment]
https://b2evolution.net/man/skin-folders

> All the files related to Skins/Themes are located in a sub-folder called /skins/ at the root of your b2evolution installation.

No they're not. 

Another instance. 
ufld_icons 
Overriding core css files to change colors on the most basic elements on the page just doesn't make sense to me. They can hardly be called skins if they don't even control the colors of basic things like nav and social icons.
`.ufld_icon_links a {
    display: inline-block;
    text-decoration: none;
    color: #FFF;
    background: #ddd;
    border-radius: 50%;
    width: 40px;
    height: 40px;
    margin: 2px;`
All coming from rsc/build/bootstrap-b2evo_base.min.css
boostrap manual skin style.css has
`.evo_container__page_top .ufld_icon_links {
  text-align: right;
}`
and that's it. Just seem backwards to me.

`.nav>li>a`

I was trying to decrease padding so I don't think that would work. I did try it but maybe I didn't do it right. 
I got it done though.

I'm closing this since it's just me bitching about a pet peeve evidently. My son was diagnosed with autism years ago so perhaps I'm an un-diagnosed adult autist.

**Comment by fplanque** [comment]
Excerpt now added to https://b2evolution.net/man/howto-add-custom-css:

The Cascading Style Sheets concept
CSS means Cascading Style Sheets. It means that some styles can be defined in a generic way which can later be overridden by another rule in another Style Sheet. For example, b2evolution’s core CSS files may define that visibility statuses like "Public" or "Community" will be displayed as a round pill. Then another rule will define a different color for each of these pills, without specifying that it is round again. Then a specific skin may actually want to display those as rectangles. It will override the "rounded corners" property without touching the colors.

The reason why skins include generic styles is that when the core adds some news features, for example a new visibility state like "Private" which should display in red, it will immediately be available to all skins, without necessarily needing to update those skins.

Another reasons is to support the wide variety of widgets. It is not possible to expect each skin to have stylings for each widget and to keep up with each new widget that comes out. All widgets not explicitly restyled by a skin will use the styles defined by the core CSS files.

> I was trying to decrease padding so I don't think that would work.

Yes it would.
